import { createSwaggerSpec } from 'next-swagger-doc';

export const getApiDocs = async () => {
    const spec = createSwaggerSpec({
        apiFolder: 'src/app/api',
        definition: {
            openapi: '3.0.0',
            info: {
                title: 'Blood Management System API Documentation',
                version: '1.0.0',
                description: 'Complete OpenAPI 3.0 specification covering authentication, health checks, and resource manipulation endpoints natively generated by Next.js App Router endpoints.',
            },
            servers: [
                {
                    url: 'http://localhost:3000',
                    description: 'Local Development Server',
                },
                {
                    url: 'https://production.bloodos.com',
                    description: 'Production ECR Deployment AWS Bound',
                },
            ],
            components: {
                securitySchemes: {
                    BearerAuth: {
                        type: 'http',
                        scheme: 'bearer',
                        bearerFormat: 'JWT',
                    },
                },
            },
            security: [
                {
                    BearerAuth: [],
                },
            ],
        },
    });
    return spec;
};
